# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-05-25 01:14-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:107
msgid "failed to load pilot"
msgstr "epäonnistui lataamaan pilottia"

#: pypilot/autopilot.py:110
msgid "Available Pilots"
msgstr "Saatavilla olevat lentäjät"

#: pypilot/autopilot.py:136
msgid "warning: failed to open special file"
msgstr "varoitus: erikoistiedoston avaaminen epäonnistui"

#: pypilot/autopilot.py:136
msgid "for writing"
msgstr "kirjoittamista varten"

#: pypilot/autopilot.py:137
msgid "cannot stroke the watchdog"
msgstr "ei voi silittää vahtikoiraa"

#: pypilot/autopilot.py:141
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"varoitus: autopilotin prosessin tekeminen reaaliaikaiseksi epäonnistui"

#: pypilot/autopilot.py:309
msgid "server/client is running too _slowly_"
msgstr "palvelin / asiakas toimii liian _hitaasti_"

#: pypilot/autopilot.py:315
msgid "sensors is running too _slowly_"
msgstr "anturit käyvät liian hitaasti"

#: pypilot/autopilot.py:365
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotin rutiini toimii liian hitaasti"

#: pypilot/autopilot.py:370
msgid "servo is running too _slowly_"
msgstr "servo toimii liian hitaasti"

#: pypilot/boatimu.py:34
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-kirjastoa ei löydy, asenna se"

#: pypilot/boatimu.py:57
msgid "Using settings file"
msgstr "Asetustiedoston käyttäminen"

#: pypilot/boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "VIRHE: IMU: ta ei havaittu"

#: pypilot/boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "VIRHE: IMU Init epäonnistui, inertiatietoja ei ole käytettävissä"

#: pypilot/boatimu.py:127
msgid "warning, failed to make imu process realtime"
msgstr "varoitus, epäonnistui imu-prosessin tekeminen reaaliajassa"

#: pypilot/boatimu.py:129
msgid "made imu process realtime"
msgstr "teki imuprosessista reaaliaikaisen"

#: pypilot/boatimu.py:141
msgid "setting initial gyro bias"
msgstr "alkuperäisen gyro-biasin asettaminen"

#: pypilot/boatimu.py:157
msgid "imu process failed to keep time"
msgstr "imu-prosessi ei onnistunut pitämään aikaa"

#: pypilot/boatimu.py:165
msgid "failed to read IMU!"
msgstr "epäonnistui lukemaan IMU: ta!"

#: pypilot/boatimu.py:197
msgid "imu rate set to rate"
msgstr "imu-kurssi asetettu koroksi"

#: pypilot/boatimu.py:211
msgid "too high standing gyro bias, resetting sensors"
msgstr "liian korkea seisova gyro-bias, antureiden nollaaminen"

#: pypilot/boatimu.py:216
msgid "compass out of range, resetting"
msgstr "kompassi kantaman ulkopuolella, nollaus"

#: pypilot/boatimu.py:308
msgid "warning, failed to make calibration process other"
msgstr "varoitus, kalibrointiprosessia ei tehty muuksi"

#: pypilot/boatimu.py:310
msgid "warning, failed to make calibration process idle, trying renice"
msgstr "varoitus, kalibrointiprosessin siirtäminen lepotilaan epäonnistui"

#: pypilot/boatimu.py:312
msgid "warning, failed to renice calibration process"
msgstr "varoitus, kalibrointiprosessin muuttaminen epäonnistui"

#: pypilot/boatimu.py:320
msgid "calibration loaded, starting"
msgstr "kalibrointi ladattu, alkaa"

#: pypilot/boatimu.py:323
msgid "failed import calibration fit"
msgstr "epäonnistunut tuontikalibrointisovellus"

#: pypilot/boatimu.py:339
msgid "terminate calibration process"
msgstr "lopeta kalibrointi"

#: pypilot/boatimu.py:429
msgid "accel values invalid"
msgstr "Accel-arvot ovat virheellisiä"

#: pypilot/bufferedsocket.py:56
msgid "overflow in pypilot udp socket"
msgstr "ylivuoto pypilot udp -liitännässä"

#: pypilot/bufferedsocket.py:61
msgid "overflow in pypilot socket"
msgstr "pypilot-pistorasian ylivuoto"

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr "udp-paketin lähettäminen epäonnistui"

#: pypilot/bufferedsocket.py:80
msgid "pypilot socket failed to send to"
msgstr "pypilot-pistorasian lähettäminen epäonnistui"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "liittimen lähettäminen kesti liian kauan!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "pistorasian lähetysvirhe"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "pypilot-pistorasian poikkeus"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"palatessasi pythonin estämättömään pistorasiaan, kuluttaa enemmän "
"prosessoria"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "pistorasian lähetysvirhe palvelimen huuhtelussa"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "virhe tietojen vastaanottamisessa"

#: pypilot/calibration_fit.py:39
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"tieteellisen kirjaston lataaminen epäonnistui, kalibrointipäivitystä ei voi "
"suorittaa!"

#: pypilot/client.py:97
msgid "warning, registering existing value:"
msgstr "varoitus, olemassa olevan arvon rekisteröinti:"

#: pypilot/client.py:155
msgid "failed to read config file:"
msgstr "määritystiedoston lukeminen epäonnistui:"

#: pypilot/client.py:186
msgid "failed to write config file:"
msgstr "määritystiedoston kirjoittaminen epäonnistui:"

#: pypilot/client.py:188
msgid "Exception writing config file:"
msgstr "Poikkeuksen kirjoittava määritystiedosto:"

#: pypilot/client.py:265
msgid "invalid message from server:"
msgstr "virheellinen viesti palvelimelta:"

#: pypilot/client.py:281
msgid "warning, pypilot client aleady has connection"
msgstr "varoitus, pypilot-asiakkaalla on jo yhteys"

#: pypilot/client.py:301
msgid "connect failed to"
msgstr "yhteyden muodostaminen epäonnistui"

#: pypilot/client.py:388
msgid "failed to connect to"
msgstr "yhteyden muodostaminen epäonnistui"

#: pypilot/client.py:445
msgid "usage"
msgstr "käyttö"

#: pypilot/client.py:448
msgid "set the host or ip address"
msgstr "aseta isäntä- tai ip-osoite"

#: pypilot/client.py:449
msgid "print info about each value type"
msgstr "tulosta tiedot jokaisesta arvotyypistä"

#: pypilot/client.py:450
msgid "continuous watch"
msgstr "jatkuva katselu"

#: pypilot/client.py:451
msgid "show this message"
msgstr "näytä tämä viesti"

#: pypilot/client.py:478
msgid "failed to retrieve value list!"
msgstr "arvoluettelon noutaminen epäonnistui!"

#: pypilot/client.py:489
msgid "timeout retrieving"
msgstr "aikakatkaisun haku"

#: pypilot/client.py:492
msgid "missing"
msgstr "puuttuu"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot epäonnistui tarvittavien moduulien tuomisessa. Unohtuiko suorittaa "
"sudo python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "gpsd kytketty"

#: pypilot/gpsd.py:48
msgid "gpsd failed to connect"
msgstr "gpsd-yhteyden muodostaminen epäonnistui"

#: pypilot/gpsd.py:53
msgid "exception connecting to gps"
msgstr "GPS: ään yhdistävä poikkeus"

#: pypilot/gpsd.py:57
msgid "gpsd disconnected"
msgstr "gpsd katkaistu"

#: pypilot/gpsd.py:71
msgid "gpsd PROBE success"
msgstr "gpsd PROBE menestys"

#: pypilot/gpsd.py:79
msgid "gpsd probe failed"
msgstr "GPSD-koetin epäonnistui"

#: pypilot/gpsd.py:102
msgid "gpsd deactivated"
msgstr "gpsd deaktivoitu"

#: pypilot/gpsd.py:135
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd ei onnistunut määrittämään laitteen sarjasiirtonopeutta"

#: pypilot/gpsd.py:152
msgid "gpsd timeout from lack of data"
msgstr "GPSD-aikakatkaisu tietojen puutteesta"

#: pypilot/gpsd.py:167
msgid "gpsd received invalid message"
msgstr "gpsd vastaanotti virheellisen viestin"

#: pypilot/gpsd.py:212
msgid "gpsd got flag for pipe:"
msgstr "gpsd sai lipun putkelle:"

#: pypilot/gpsd.py:221
msgid "gpsd serial probe"
msgstr "gpsd-sarjakoetin"

#: pypilot/nmea.py:87
msgid "nmea failed to parse gps"
msgstr "nmea ei pystynyt jäsentämään GPS: ää"

#: pypilot/nmea.py:127
msgid "nmea failed to parse wind"
msgstr "nmea ei pystynyt jäsentämään tuulta"

#: pypilot/nmea.py:189
msgid "exception parsing apb"
msgstr "poikkeus jäsentää apb"

#: pypilot/nmea.py:277
msgid "unhandled nmea pipe string"
msgstr "käsittelemätön nmea-putkijono"

#: pypilot/nmea.py:327
msgid "lost serial"
msgstr "kadonnut sarja"

#: pypilot/nmea.py:350
msgid "nmea got flag for process pipe:"
msgstr "nmea sai lipun prosessiputkelle:"

#: pypilot/nmea.py:371
msgid "is another process accessing it?"
msgstr "onko toinen prosessi pääsy siihen?"

#: pypilot/nmea.py:373
msgid "serial device timed out"
msgstr "sarjalaite aikakatkaistiin"

#: pypilot/nmea.py:429
msgid "failed to open"
msgstr "epäonnistui avaaminen"

#: pypilot/nmea.py:482
msgid "nmea server on port"
msgstr "nmea-palvelin portissa"

#: pypilot/nmea.py:482
msgid "bind failed."
msgstr "sidonta epäonnistui."

#: pypilot/nmea.py:484
msgid "listening on port"
msgstr "kuuntelee satamassa"

#: pypilot/nmea.py:484
msgid "for nmea connections"
msgstr "nmea-yhteyksille"

#: pypilot/nmea.py:550
msgid "nmea server has too many connections"
msgstr "nmea-palvelimella on liian monta yhteyttä"

#: pypilot/nmea.py:576
msgid "nmea sock not in sockets!"
msgstr "nmea-sukka ei ole pistorasioissa!"

#: pypilot/nmea.py:587
msgid "nmea failed to unregister socket"
msgstr "nmea ei onnistunut poistamaan pistorasian rekisteröintiä"

#: pypilot/nmea.py:592
msgid "nmea failed to remove fd"
msgstr "nmea ei onnistunut poistamaan fd: tä"

#: pypilot/nmea.py:597
msgid "nmea failed to remove address"
msgstr "nmea ei onnistunut poistamaan osoitetta"

#: pypilot/nmea.py:610
msgid "connected to"
msgstr "yhdistetty"

#: pypilot/nmea.py:610
msgid "in"
msgstr "sisään"

#: pypilot/nmea.py:610
msgid "seconds"
msgstr "sekuntia"

#: pypilot/nmea.py:614
msgid "nmea client failed to connect to"
msgstr "nmea-asiakas epäonnistui yhteyden muodostamiseen"

#: pypilot/nmea.py:641
msgid "poll took too long in nmea process!"
msgstr "kysely kesti liian kauan nmea-prosessissa!"

#: pypilot/nmea.py:648
msgid "nmea bridge lost server connection"
msgstr "nmea-silta katosi palvelinyhteyden"

#: pypilot/nmea.py:651
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea-silta menetti putken autopilotille"

#: pypilot/nmea.py:670
msgid "nmea bridge unhandled poll flag"
msgstr "nmea-silta käsittelemätön kyselylippu"

#: pypilot/nmea.py:707
msgid "failed to create nmea socket as host:port"
msgstr "ei luonut nmea-liitäntää isäntänä: portti"

#: pypilot/nmea.py:713
msgid "nmea process loop too slow:"
msgstr "nmea-prosessisilmukka liian hidas:"

#: pypilot/nonblockingpipe.py:41
msgid "error pipe block on recv!"
msgstr "virhe putkilohko recv!"

#: pypilot/nonblockingpipe.py:43
msgid "failed to recv nonblocking pipe!"
msgstr "epäonnistui rekvisiittaista putkea!"

#: pypilot/nonblockingpipe.py:70
msgid "pipe full"
msgstr "putki täynnä"

#: pypilot/nonblockingpipe.py:70
msgid "cannot send"
msgstr "ei voi lähettää"

#: pypilot/nonblockingpipe.py:90 pypilot/nonblockingpipe.py:146
msgid "failed to decode data socket!"
msgstr "ei onnistunut purkamaan datapistoketta!"

#: pypilot/nonblockingpipe.py:104
msgid "failed to encode data socket!"
msgstr "ei onnistunut koodaamaan datapistoketta!"

#: pypilot/nonblockingpipe.py:156
msgid "failed write"
msgstr "epäonnistui kirjoittaminen"

#: pypilot/pyjson.py:15
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"VAROITUS: python ujson -kirjasto epäonnistui, jäsentäminen kuluttaa enemmän "
"prosessoria"

#: pypilot/rudder.py:118
msgid "bad rudder calibration"
msgstr "huono peräsimen kalibrointi"

#: pypilot/rudder.py:122
msgid "bad servo rudder calibration"
msgstr "huono servopyörän kalibrointi"

#: pypilot/rudder.py:194
msgid "servo rudder autogain failed"
msgstr "servo-peräsimen automaattinen vahvistus epäonnistui"

#: pypilot/sensors.py:43
msgid "sensor found"
msgstr "anturi löytyi"

#: pypilot/sensors.py:192
msgid "unknown data parsed!"
msgstr "tuntemattomia tietoja on jäsennelty!"

#: pypilot/serialprobe.py:31
msgid "error reading"
msgstr "virhe luettaessa"

#: pypilot/serialprobe.py:87
msgid "found more devices by path"
msgstr "löysi lisää laitteita polun mukaan"

#: pypilot/serialprobe.py:119
msgid "removing gps device"
msgstr "GPS-laitteen poistaminen"

#: pypilot/serialprobe.py:195
msgid "no pyudev module! will scan usb devices often!"
msgstr "ei pyudev-moduulia! skannaa usb-laitteita usein!"

#: pypilot/serialprobe.py:357
msgid "success"
msgstr "menestys"

#: pypilot/serialprobe.py:365
msgid "failed to record device"
msgstr "laitteen tallennus epäonnistui"

#: pypilot/server.py:97
msgid "ERROR no connections in watch"
msgstr "VIRHE ei yhteyttä kellossa"

#: pypilot/server.py:200
msgid "remove duplicate udp connection"
msgstr "Poista päällekkäinen udp-yhteys"

#: pypilot/server.py:340 ui/boatplot.py:110
msgid "failed to load"
msgstr "lataus epäonnistui"

#: pypilot/server.py:351
msgid "backup data failed as well"
msgstr "varmuuskopiointi epäonnistui"

#: pypilot/server.py:379
msgid "failed to write"
msgstr "ei kirjoittanut"

#: pypilot/server.py:436
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: sidonta epäonnistui; jo palvelinta?"

#: pypilot/server.py:498
msgid "persistent store took too long!"
msgstr "jatkuva myymälä kesti liian kauan!"

#: pypilot/server.py:514
msgid "max connections reached"
msgstr "maksimiliitännät saavutettu"

#: pypilot/server.py:517
msgid "server add socket"
msgstr "palvelimen lisäyspistoke"

#: pypilot/server.py:527
msgid "internal pipe closed, server exiting"
msgstr "sisäinen putki suljettu, palvelin poistuu"

#: pypilot/server.py:579
msgid "server socket closed from flush!!"
msgstr "palvelinpistoke suljettu huuhtelusta!"

#: pypilot/servo.py:449
msgid "servo calibration invalid"
msgstr "servokalibrointi on virheellinen"

#: pypilot/servo.py:557
msgid "failed to open servo on:"
msgstr "epäonnistui avaamasta servoa:"

#: pypilot/servo.py:564
msgid "failed set nonblocking/exclusive"
msgstr "epäonnistunut asetettu esto / yksinoikeus"

#: pypilot/servo.py:595
msgid "found"
msgstr "löytyi"

#: pypilot/servo.py:716
msgid "loading servo calibration"
msgstr "servokalibroinnin lataus"

#: pypilot/servo.py:720
msgid "WARNING: using default servo calibration!!"
msgstr "VAROITUS: oletus servokalibrointi !!"

#: pypilot/servo.py:729
msgid "probing"
msgstr "koettelemalla"

#: pypilot/servo.py:745
msgid "arduino servo detected"
msgstr "arduino-servo havaittu"

#: pypilot/servo.py:754
msgid "device needed for option"
msgstr "tarvittava laite"

#: pypilot/signalk.py:67
msgid "read token"
msgstr "lukea tunnusta"

#: pypilot/signalk.py:70
msgid "failed to read token"
msgstr "tunnuksen lukeminen epäonnistui"

#: pypilot/signalk.py:77
msgid "failed to"
msgstr "epäonnistui"

#: pypilot/signalk.py:77
msgid "autodetection not possible"
msgstr "automaattinen tunnistus ei ole mahdollista"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "try"
msgstr "yrittää"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "or"
msgstr "tai"

#: pypilot/signalk.py:109
msgid "service removed"
msgstr "palvelu poistettu"

#: pypilot/signalk.py:113
msgid "signalk server lost"
msgstr "signalk-palvelin menetetty"

#: pypilot/signalk.py:116
msgid "service add"
msgstr "palvelu lisää"

#: pypilot/signalk.py:130
msgid "server found"
msgstr "palvelin löydetty"

#: pypilot/signalk.py:139
msgid "probe"
msgstr "koetin"

#: pypilot/signalk.py:143
msgid "could not"
msgstr "ei pystynyt"

#: pypilot/signalk.py:153
msgid "failed to retrieve/parse data from"
msgstr "epäonnistui tietojen noutamisesta / jäsentämisestä"

#: pypilot/signalk.py:156
msgid "signalk found"
msgstr "opaste löytyi"

#: pypilot/signalk.py:168
msgid "see if token is ready"
msgstr "katso onko tunniste valmis"

#: pypilot/signalk.py:174
msgid "received token"
msgstr "saanut tunnuksen"

#: pypilot/signalk.py:180
msgid "failed to store token"
msgstr "tunnuksen tallentaminen epäonnistui"

#: pypilot/signalk.py:184
msgid "error requesting access"
msgstr "virhe pyydettäessä käyttöoikeutta"

#: pypilot/signalk.py:203
msgid "signalk request access url"
msgstr "opasteiden käyttöoikeuksien URL-osoite"

#: pypilot/signalk.py:205
msgid "signalk error requesting access"
msgstr "opasteiden käyttöoikeutta pyydettäessä"

#: pypilot/signalk.py:212
msgid "cannot create connection:"
msgstr "ei voi luoda yhteyttä:"

#: pypilot/signalk.py:226
msgid "failed to connect"
msgstr "ei voida yhdistää"

#: pypilot/signalk.py:270
msgid "signalk connected to"
msgstr "opaste yhdistetty"

#: pypilot/signalk.py:313
msgid "signalk failed to parse"
msgstr "opasteiden jäsentäminen epäonnistui"

#: pypilot/signalk.py:331
msgid "Exception converting signalk->pypilot"
msgstr "Poikkeus muuntaa opasteet-> pypilot"

#: pypilot/signalk.py:345
msgid "received"
msgstr "sai"

#: pypilot/signalk.py:391
msgid "signalk failed to send"
msgstr "opasteiden lähetys epäonnistui"

#: pypilot/signalk.py:404
msgid "signalk failed to parse msg:"
msgstr "signalk ei jäsennä viestiä:"

#: pypilot/values.py:131
msgid "invalid initial value for range property"
msgstr "alueen omaisuuden alkuarvo on virheellinen"

#: pypilot/values.py:180
msgid "invalid set"
msgstr "virheellinen sarja"

#: pypilot/pilots/__init__.py:25
msgid "ERROR loading"
msgstr "Virhe ladattaessa"

#: ui/autopilot_calibration.py:167
msgid "exception in calibration:"
msgstr "poikkeus kalibroinnissa:"

#: ui/autopilot_control.py:265
msgid "warning: unhandled message"
msgstr "varoitus: käsittelemätön viesti"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilottiohjaus"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Sinä"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:455 ui/autopilot_control_ui.py:732
msgid "N/A"
msgstr "N / A"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "N / A"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "N / A"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "satamaan"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "oikealle"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Lentäjä"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:420
msgid "Compass"
msgstr "Kompassi"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Tuuli"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Todellinen tuuli"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Keskusta"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Laajuus"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Asiakas"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "&Kalibrointi"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "kiinni"

#: ui/autopilot_control_ui.py:299 ui/autopilot_control_ui.py:529
#: ui/autopilot_control_ui.py:649
msgid "Calibration"
msgstr "Kalibrointi"

#: ui/autopilot_control_ui.py:349
msgid "Boat is level"
msgstr "Vene on vaakasuorassa"

#: ui/autopilot_control_ui.py:356 ui/client_wx.py:159 ui/scope_ui.py:94
msgid "Reset"
msgstr "Nollaa"

#: ui/autopilot_control_ui.py:377
msgid "Alignment"
msgstr "Kohdistus"

#: ui/autopilot_control_ui.py:394
msgid "Heading"
msgstr "Otsikko"

#: ui/autopilot_control_ui.py:399 ui/autopilot_control_ui.py:465
#: ui/autopilot_control_ui.py:475
msgid "     N/A     "
msgstr "N / A"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:755
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:418
msgid "Coords"
msgstr "Coords"

#: ui/autopilot_control_ui.py:420
msgid "Sea"
msgstr "Meri"

#: ui/autopilot_control_ui.py:420
msgid "Boat"
msgstr "Vene"

#: ui/autopilot_control_ui.py:443 ui/client_wx.py:52
msgid "Scope"
msgstr "Soveltamisala"

#: ui/autopilot_control_ui.py:450
msgid "Pitch"
msgstr "Piki"

#: ui/autopilot_control_ui.py:460
msgid "Roll"
msgstr "Rullaa"

#: ui/autopilot_control_ui.py:470
msgid "Heel"
msgstr "Kantapää"

#: ui/autopilot_control_ui.py:497
msgid "alignment"
msgstr "kohdistus"

#: ui/autopilot_control_ui.py:539 ui/autopilot_control_ui.py:659
msgid "Calibration Age"
msgstr "Kalibrointiaika"

#: ui/autopilot_control_ui.py:556 ui/autopilot_control_ui.py:676
msgid "Clear"
msgstr "Asia selvä"

#: ui/autopilot_control_ui.py:559 ui/autopilot_control_ui.py:679
msgid "calibration locked"
msgstr "kalibrointi lukittu"

#: ui/autopilot_control_ui.py:582
msgid "accel"
msgstr "Accel"

#: ui/autopilot_control_ui.py:613
msgid "Sigma Points"
msgstr "Sigma-pisteet"

#: ui/autopilot_control_ui.py:620
msgid "local history"
msgstr "paikallista historiaa"

#: ui/autopilot_control_ui.py:627
msgid "current"
msgstr "nykyinen"

#: ui/autopilot_control_ui.py:634
msgid "Calibration Points"
msgstr "Kalibrointipisteet"

#: ui/autopilot_control_ui.py:703
msgid "compass"
msgstr "kompassi"

#: ui/autopilot_control_ui.py:713
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Paina kutakin painiketta, kun peräsin on oikeassa asennossa kalibrointia "
"varten."

#: ui/autopilot_control_ui.py:727
msgid "Rudder"
msgstr "Peräsin"

#: ui/autopilot_control_ui.py:742
msgid "Reset Calibration"
msgstr "Nollaa kalibrointi"

#: ui/autopilot_control_ui.py:752
msgid "Rudder Is Centered"
msgstr "Peräsin on keskitetty"

#: ui/autopilot_control_ui.py:760 ui/autopilot_control_ui.py:773
#: ui/autopilot_control_ui.py:786
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:765
msgid "Rudder is Starboard Range"
msgstr "Peräsin on oikeanpuoleinen alue"

#: ui/autopilot_control_ui.py:768
msgid "Scale"
msgstr "Mittakaava"

#: ui/autopilot_control_ui.py:778
msgid "Rudder is Port Range"
msgstr "Peräsin on Port Range"

#: ui/autopilot_control_ui.py:781
msgid "Non Linearity"
msgstr "Epälineaarisuus"

#: ui/autopilot_control_ui.py:798
msgid " range +-"
msgstr "alue + -"

#: ui/autopilot_control_ui.py:806
msgid "degrees"
msgstr "astetta"

#: ui/autopilot_control_ui.py:825
msgid "rudder"
msgstr "peräsin"

#: ui/autopilot_control_ui.py:827
msgid "settings"
msgstr "asetukset"

#: ui/boatplot.py:26
msgid "failed to load pywavefront:"
msgstr "pywavefrontin lataaminen epäonnistui:"

#: ui/boatplot.py:56
msgid "invalid display dimensions"
msgstr "virheelliset näytön mitat"

#: ui/boatplot.py:111
msgid "Did you add the pypilot_data repository?"
msgstr "Lisäsitkö pypilot_data-arkiston?"

#: ui/boatplot.py:161
msgid "not found, texture compass cannot be used"
msgstr "ei löydy, tekstuurikompassia ei voida käyttää"

#: ui/client_wx.py:48
msgid "Refresh"
msgstr "virkistää"

#: ui/client_wx.py:190
msgid "Connected"
msgstr "Yhdistetty"

#: ui/client_wx.py:192
msgid "Disconnected"
msgstr "Yhteys katkaistu"

#: ui/client_wx.py:219
msgid "warning, invalid choice value specified"
msgstr "varoitus, virheellinen valinnan arvo määritetty"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "pypilot-soveltamisala"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Nolla"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skaalaa +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Asteikko -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Siirtymä \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Jäätykää"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Aika"

#: ui/scope_wx.py:68
msgid "values not found:"
msgstr "arvoja ei löydy:"
