# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-05-25 01:14-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:107
msgid "failed to load pilot"
msgstr "mislyktes i å laste pilot"

#: pypilot/autopilot.py:110
msgid "Available Pilots"
msgstr "Tilgjengelige piloter"

#: pypilot/autopilot.py:136
msgid "warning: failed to open special file"
msgstr "advarsel: kunne ikke åpne spesialfil"

#: pypilot/autopilot.py:136
msgid "for writing"
msgstr "for skriving"

#: pypilot/autopilot.py:137
msgid "cannot stroke the watchdog"
msgstr "kan ikke stryke vakthunden"

#: pypilot/autopilot.py:141
msgid "warning: failed to make autopilot process realtime"
msgstr "advarsel: kunne ikke gjøre autopilotprosessen i sanntid"

#: pypilot/autopilot.py:309
msgid "server/client is running too _slowly_"
msgstr "server / klient kjører også _slowly_"

#: pypilot/autopilot.py:315
msgid "sensors is running too _slowly_"
msgstr "sensorene går for sakte"

#: pypilot/autopilot.py:365
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotrutinen går for sakte"

#: pypilot/autopilot.py:370
msgid "servo is running too _slowly_"
msgstr "servo går for sakte"

#: pypilot/boatimu.py:34
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-biblioteket ble ikke oppdaget. Installer det"

#: pypilot/boatimu.py:57
msgid "Using settings file"
msgstr "Bruker innstillingsfil"

#: pypilot/boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "FEIL: Ingen IMU oppdaget"

#: pypilot/boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEIL: IMU Init mislyktes, ingen treghetsdata tilgjengelig"

#: pypilot/boatimu.py:127
msgid "warning, failed to make imu process realtime"
msgstr "advarsel, klarte ikke å gjøre imu-prosessen i sanntid"

#: pypilot/boatimu.py:129
msgid "made imu process realtime"
msgstr "laget imu-prosessen i sanntid"

#: pypilot/boatimu.py:141
msgid "setting initial gyro bias"
msgstr "sette innledende gyro bias"

#: pypilot/boatimu.py:157
msgid "imu process failed to keep time"
msgstr "imu-prosessen klarte ikke å holde tiden"

#: pypilot/boatimu.py:165
msgid "failed to read IMU!"
msgstr "mislyktes i å lese IMU!"

#: pypilot/boatimu.py:197
msgid "imu rate set to rate"
msgstr "imu rate satt til rate"

#: pypilot/boatimu.py:211
msgid "too high standing gyro bias, resetting sensors"
msgstr "for høy stående gyroforstyrrelse, tilbakestiller sensorer"

#: pypilot/boatimu.py:216
msgid "compass out of range, resetting"
msgstr "kompass utenfor rekkevidde, tilbakestilles"

#: pypilot/boatimu.py:308
msgid "warning, failed to make calibration process other"
msgstr "advarsel, klarte ikke å gjøre kalibreringsprosessen annen"

#: pypilot/boatimu.py:310
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"advarsel, klarte ikke å gjøre kalibreringsprosessen inaktiv, og prøvde å "
"nekte"

#: pypilot/boatimu.py:312
msgid "warning, failed to renice calibration process"
msgstr "advarsel, mislyktes i å nekte kalibreringsprosessen"

#: pypilot/boatimu.py:320
msgid "calibration loaded, starting"
msgstr "kalibrering lastet, starter"

#: pypilot/boatimu.py:323
msgid "failed import calibration fit"
msgstr "mislykket importkalibreringstilpasning"

#: pypilot/boatimu.py:339
msgid "terminate calibration process"
msgstr "avslutte kalibreringsprosessen"

#: pypilot/boatimu.py:429
msgid "accel values invalid"
msgstr "accel-verdiene er ugyldige"

#: pypilot/bufferedsocket.py:56
msgid "overflow in pypilot udp socket"
msgstr "overløp i pypilot udp-stikkontakt"

#: pypilot/bufferedsocket.py:61
msgid "overflow in pypilot socket"
msgstr "overløp i pypilotkontakt"

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr "kunne ikke sende udp-pakken"

#: pypilot/bufferedsocket.py:80
msgid "pypilot socket failed to send to"
msgstr "pypilot-kontakten kunne ikke sendes til"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "socket send tok for lang tid!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "stikkontaktfeil"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "unntak for pypilotuttak"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"faller tilbake til python ikke-blokkerende stikkontakt, vil forbruke mer CPU"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "socket sende feil i serveren flush"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "feil ved mottak av data"

#: pypilot/calibration_fit.py:39
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"kunne ikke laste vitenskapelig bibliotek, kan ikke utføre "
"kalibreringsoppdatering!"

#: pypilot/client.py:97
msgid "warning, registering existing value:"
msgstr "advarsel, registrere eksisterende verdi:"

#: pypilot/client.py:155
msgid "failed to read config file:"
msgstr "mislyktes i å lese konfigurasjonsfilen:"

#: pypilot/client.py:186
msgid "failed to write config file:"
msgstr "mislyktes i å skrive konfigurasjonsfil:"

#: pypilot/client.py:188
msgid "Exception writing config file:"
msgstr "Unntak for å skrive konfigurasjonsfil:"

#: pypilot/client.py:265
msgid "invalid message from server:"
msgstr "ugyldig melding fra server:"

#: pypilot/client.py:281
msgid "warning, pypilot client aleady has connection"
msgstr "advarsel, har pypilot-klienten allerede tilkobling"

#: pypilot/client.py:301
msgid "connect failed to"
msgstr "koble mislyktes i"

#: pypilot/client.py:388
msgid "failed to connect to"
msgstr "kunne ikke koble til"

#: pypilot/client.py:445
msgid "usage"
msgstr "bruk"

#: pypilot/client.py:448
msgid "set the host or ip address"
msgstr "angi verten eller ip-adressen"

#: pypilot/client.py:449
msgid "print info about each value type"
msgstr "skrive ut info om hver verditype"

#: pypilot/client.py:450
msgid "continuous watch"
msgstr "kontinuerlig klokke"

#: pypilot/client.py:451
msgid "show this message"
msgstr "vis denne meldingen"

#: pypilot/client.py:478
msgid "failed to retrieve value list!"
msgstr "mislyktes i å hente verdilisten!"

#: pypilot/client.py:489
msgid "timeout retrieving"
msgstr "timeout henting"

#: pypilot/client.py:492
msgid "missing"
msgstr "savnet"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kunne ikke importere nødvendige moduler. Glemte du å kjøre sudo "
"python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "GPSD tilkoblet"

#: pypilot/gpsd.py:48
msgid "gpsd failed to connect"
msgstr "gpsd kunne ikke koble til"

#: pypilot/gpsd.py:53
msgid "exception connecting to gps"
msgstr "unntak som kobler til GPS"

#: pypilot/gpsd.py:57
msgid "gpsd disconnected"
msgstr "gpsd frakoblet"

#: pypilot/gpsd.py:71
msgid "gpsd PROBE success"
msgstr "gpsd PROBE suksess"

#: pypilot/gpsd.py:79
msgid "gpsd probe failed"
msgstr "gpsd-sonde mislyktes"

#: pypilot/gpsd.py:102
msgid "gpsd deactivated"
msgstr "GPSD deaktivert"

#: pypilot/gpsd.py:135
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd kunne ikke bestemme seriell overføringshastighet for enheten"

#: pypilot/gpsd.py:152
msgid "gpsd timeout from lack of data"
msgstr "gpsd timeout fra mangel på data"

#: pypilot/gpsd.py:167
msgid "gpsd received invalid message"
msgstr "gpsd mottok ugyldig melding"

#: pypilot/gpsd.py:212
msgid "gpsd got flag for pipe:"
msgstr "gpsd fikk flagg for pipe:"

#: pypilot/gpsd.py:221
msgid "gpsd serial probe"
msgstr "gpsd seriell sonde"

#: pypilot/nmea.py:87
msgid "nmea failed to parse gps"
msgstr "nmea kunne ikke analysere GPS"

#: pypilot/nmea.py:127
msgid "nmea failed to parse wind"
msgstr "nmea klarte ikke å analysere vind"

#: pypilot/nmea.py:189
msgid "exception parsing apb"
msgstr "unntak parsing apb"

#: pypilot/nmea.py:277
msgid "unhandled nmea pipe string"
msgstr "uhåndtert nmea rørstreng"

#: pypilot/nmea.py:327
msgid "lost serial"
msgstr "mistet serie"

#: pypilot/nmea.py:350
msgid "nmea got flag for process pipe:"
msgstr "nmea fikk flagg for prosessrør:"

#: pypilot/nmea.py:371
msgid "is another process accessing it?"
msgstr "får en annen prosess tilgang til den?"

#: pypilot/nmea.py:373
msgid "serial device timed out"
msgstr "seriell enhet ble tidsavbrutt"

#: pypilot/nmea.py:429
msgid "failed to open"
msgstr "kunne ikke åpnes"

#: pypilot/nmea.py:482
msgid "nmea server on port"
msgstr "nmea server på port"

#: pypilot/nmea.py:482
msgid "bind failed."
msgstr "bind mislyktes."

#: pypilot/nmea.py:484
msgid "listening on port"
msgstr "lytter på port"

#: pypilot/nmea.py:484
msgid "for nmea connections"
msgstr "for nmea-forbindelser"

#: pypilot/nmea.py:550
msgid "nmea server has too many connections"
msgstr "nmea server har for mange tilkoblinger"

#: pypilot/nmea.py:576
msgid "nmea sock not in sockets!"
msgstr "nmea sokk ikke i stikkontakter!"

#: pypilot/nmea.py:587
msgid "nmea failed to unregister socket"
msgstr "nmea kunne ikke avregistrere kontakten"

#: pypilot/nmea.py:592
msgid "nmea failed to remove fd"
msgstr "nmea klarte ikke å fjerne fd"

#: pypilot/nmea.py:597
msgid "nmea failed to remove address"
msgstr "nmea kunne ikke fjerne adressen"

#: pypilot/nmea.py:610
msgid "connected to"
msgstr "Koblet til"

#: pypilot/nmea.py:610
msgid "in"
msgstr "i"

#: pypilot/nmea.py:610
msgid "seconds"
msgstr "sekunder"

#: pypilot/nmea.py:614
msgid "nmea client failed to connect to"
msgstr "nmea-klienten kunne ikke koble til"

#: pypilot/nmea.py:641
msgid "poll took too long in nmea process!"
msgstr "avstemningen tok for lang tid i nmea-prosessen!"

#: pypilot/nmea.py:648
msgid "nmea bridge lost server connection"
msgstr "nmea bridge mistet serverforbindelse"

#: pypilot/nmea.py:651
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge mistet rør til autopilot"

#: pypilot/nmea.py:670
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge uhåndtert avstemningsflagg"

#: pypilot/nmea.py:707
msgid "failed to create nmea socket as host:port"
msgstr "mislyktes i å opprette nmea-sokkel som vert: port"

#: pypilot/nmea.py:713
msgid "nmea process loop too slow:"
msgstr "nmea prosessløkke for sakte:"

#: pypilot/nonblockingpipe.py:41
msgid "error pipe block on recv!"
msgstr "feil rørblokk på recv!"

#: pypilot/nonblockingpipe.py:43
msgid "failed to recv nonblocking pipe!"
msgstr "mislyktes i å rekvirere ikke-blokkerende rør!"

#: pypilot/nonblockingpipe.py:70
msgid "pipe full"
msgstr "rør fullt"

#: pypilot/nonblockingpipe.py:70
msgid "cannot send"
msgstr "kan ikke sende"

#: pypilot/nonblockingpipe.py:90 pypilot/nonblockingpipe.py:146
msgid "failed to decode data socket!"
msgstr "kunne ikke dekode datakontakten!"

#: pypilot/nonblockingpipe.py:104
msgid "failed to encode data socket!"
msgstr "kunne ikke kode datakontakten!"

#: pypilot/nonblockingpipe.py:156
msgid "failed write"
msgstr "mislyktes skrive"

#: pypilot/pyjson.py:15
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ADVARSEL: Python ujson-biblioteket mislyktes, parsing vil forbruke mer CPU"

#: pypilot/rudder.py:118
msgid "bad rudder calibration"
msgstr "dårlig rorkalibrering"

#: pypilot/rudder.py:122
msgid "bad servo rudder calibration"
msgstr "dårlig servoror kalibrering"

#: pypilot/rudder.py:194
msgid "servo rudder autogain failed"
msgstr "servoror autogain mislyktes"

#: pypilot/sensors.py:43
msgid "sensor found"
msgstr "sensor funnet"

#: pypilot/sensors.py:192
msgid "unknown data parsed!"
msgstr "ukjente data analysert!"

#: pypilot/serialprobe.py:31
msgid "error reading"
msgstr "feillesing"

#: pypilot/serialprobe.py:87
msgid "found more devices by path"
msgstr "fant flere enheter etter sti"

#: pypilot/serialprobe.py:119
msgid "removing gps device"
msgstr "fjerne GPS-enhet"

#: pypilot/serialprobe.py:195
msgid "no pyudev module! will scan usb devices often!"
msgstr "ingen pyudev-modul! vil skanne USB-enheter ofte!"

#: pypilot/serialprobe.py:357
msgid "success"
msgstr "suksess"

#: pypilot/serialprobe.py:365
msgid "failed to record device"
msgstr "kunne ikke registrere enheten"

#: pypilot/server.py:97
msgid "ERROR no connections in watch"
msgstr "FEIL ingen tilkoblinger i klokken"

#: pypilot/server.py:200
msgid "remove duplicate udp connection"
msgstr "Fjern duplikat UDP-tilkobling"

#: pypilot/server.py:340 ui/boatplot.py:110
msgid "failed to load"
msgstr "kunne ikke laste"

#: pypilot/server.py:351
msgid "backup data failed as well"
msgstr "sikkerhetskopieringsdata mislyktes også"

#: pypilot/server.py:379
msgid "failed to write"
msgstr "klarte ikke å skrive"

#: pypilot/server.py:436
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: bind mislyktes; kjører du allerede en server?"

#: pypilot/server.py:498
msgid "persistent store took too long!"
msgstr "vedvarende butikk tok for lang tid!"

#: pypilot/server.py:514
msgid "max connections reached"
msgstr "maks. forbindelser nådd"

#: pypilot/server.py:517
msgid "server add socket"
msgstr "server legge til stikkontakt"

#: pypilot/server.py:527
msgid "internal pipe closed, server exiting"
msgstr "internt rør lukket, serveren avsluttes"

#: pypilot/server.py:579
msgid "server socket closed from flush!!"
msgstr "serveruttak stengt fra spyling !!"

#: pypilot/servo.py:449
msgid "servo calibration invalid"
msgstr "servokalibrering ugyldig"

#: pypilot/servo.py:557
msgid "failed to open servo on:"
msgstr "mislyktes i å åpne servo på:"

#: pypilot/servo.py:564
msgid "failed set nonblocking/exclusive"
msgstr "mislykket sett ikke-blokkering / eksklusivt"

#: pypilot/servo.py:595
msgid "found"
msgstr "funnet"

#: pypilot/servo.py:716
msgid "loading servo calibration"
msgstr "lasting av servokalibrering"

#: pypilot/servo.py:720
msgid "WARNING: using default servo calibration!!"
msgstr "ADVARSEL: bruker standard servokalibrering !!"

#: pypilot/servo.py:729
msgid "probing"
msgstr "sondering"

#: pypilot/servo.py:745
msgid "arduino servo detected"
msgstr "arduino servo oppdaget"

#: pypilot/servo.py:754
msgid "device needed for option"
msgstr "enheten som trengs for alternativet"

#: pypilot/signalk.py:67
msgid "read token"
msgstr "les token"

#: pypilot/signalk.py:70
msgid "failed to read token"
msgstr "mislyktes i å lese token"

#: pypilot/signalk.py:77
msgid "failed to"
msgstr "feilet med å"

#: pypilot/signalk.py:77
msgid "autodetection not possible"
msgstr "autodeteksjon ikke mulig"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "try"
msgstr "prøve"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "or"
msgstr "eller"

#: pypilot/signalk.py:109
msgid "service removed"
msgstr "tjenesten fjernet"

#: pypilot/signalk.py:113
msgid "signalk server lost"
msgstr "signalk-server mistet"

#: pypilot/signalk.py:116
msgid "service add"
msgstr "tjenestetillegg"

#: pypilot/signalk.py:130
msgid "server found"
msgstr "server funnet"

#: pypilot/signalk.py:139
msgid "probe"
msgstr "sonde"

#: pypilot/signalk.py:143
msgid "could not"
msgstr "kunne ikke"

#: pypilot/signalk.py:153
msgid "failed to retrieve/parse data from"
msgstr "mislyktes i å hente / analysere data fra"

#: pypilot/signalk.py:156
msgid "signalk found"
msgstr "signalt funnet"

#: pypilot/signalk.py:168
msgid "see if token is ready"
msgstr "se om token er klar"

#: pypilot/signalk.py:174
msgid "received token"
msgstr "mottatt token"

#: pypilot/signalk.py:180
msgid "failed to store token"
msgstr "mislyktes i å lagre token"

#: pypilot/signalk.py:184
msgid "error requesting access"
msgstr "feil med å be om tilgang"

#: pypilot/signalk.py:203
msgid "signalk request access url"
msgstr "signalk forespørsel om tilgang url"

#: pypilot/signalk.py:205
msgid "signalk error requesting access"
msgstr "signalk-feil som ber om tilgang"

#: pypilot/signalk.py:212
msgid "cannot create connection:"
msgstr "kan ikke opprette forbindelse:"

#: pypilot/signalk.py:226
msgid "failed to connect"
msgstr "tilkobling mislyktes"

#: pypilot/signalk.py:270
msgid "signalk connected to"
msgstr "skilt koblet til"

#: pypilot/signalk.py:313
msgid "signalk failed to parse"
msgstr "signalk kunne ikke analyseres"

#: pypilot/signalk.py:331
msgid "Exception converting signalk->pypilot"
msgstr "Unntak konvertere signalk-> pypilot"

#: pypilot/signalk.py:345
msgid "received"
msgstr "mottatt"

#: pypilot/signalk.py:391
msgid "signalk failed to send"
msgstr "signalk kunne ikke sendes"

#: pypilot/signalk.py:404
msgid "signalk failed to parse msg:"
msgstr "signalk kunne ikke analysere msg:"

#: pypilot/values.py:131
msgid "invalid initial value for range property"
msgstr "ugyldig opprinnelig verdi for områdeegenskap"

#: pypilot/values.py:180
msgid "invalid set"
msgstr "ugyldig sett"

#: pypilot/pilots/__init__.py:25
msgid "ERROR loading"
msgstr "Feil ved innlasting"

#: ui/autopilot_calibration.py:167
msgid "exception in calibration:"
msgstr "unntak i kalibrering:"

#: ui/autopilot_control.py:265
msgid "warning: unhandled message"
msgstr "advarsel: ubehandlet melding"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilotkontroll"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Du"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:455 ui/autopilot_control_ui.py:732
msgid "N/A"
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "havn"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "styrbord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:420
msgid "Compass"
msgstr "Kompass"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Vind"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Ekte vind"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Senter"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Omfang"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrering"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Lukk"

#: ui/autopilot_control_ui.py:299 ui/autopilot_control_ui.py:529
#: ui/autopilot_control_ui.py:649
msgid "Calibration"
msgstr "Kalibrering"

#: ui/autopilot_control_ui.py:349
msgid "Boat is level"
msgstr "Båten er i vater"

#: ui/autopilot_control_ui.py:356 ui/client_wx.py:159 ui/scope_ui.py:94
msgid "Reset"
msgstr "Nullstille"

#: ui/autopilot_control_ui.py:377
msgid "Alignment"
msgstr "Justering"

#: ui/autopilot_control_ui.py:394
msgid "Heading"
msgstr "Overskrift"

#: ui/autopilot_control_ui.py:399 ui/autopilot_control_ui.py:465
#: ui/autopilot_control_ui.py:475
msgid "     N/A     "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:755
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:418
msgid "Coords"
msgstr "Koordiner"

#: ui/autopilot_control_ui.py:420
msgid "Sea"
msgstr "Hav"

#: ui/autopilot_control_ui.py:420
msgid "Boat"
msgstr "Båt"

#: ui/autopilot_control_ui.py:443 ui/client_wx.py:52
msgid "Scope"
msgstr "omfang"

#: ui/autopilot_control_ui.py:450
msgid "Pitch"
msgstr "Tonehøyde"

#: ui/autopilot_control_ui.py:460
msgid "Roll"
msgstr "Rull"

#: ui/autopilot_control_ui.py:470
msgid "Heel"
msgstr "Hæl"

#: ui/autopilot_control_ui.py:497
msgid "alignment"
msgstr "Justering"

#: ui/autopilot_control_ui.py:539 ui/autopilot_control_ui.py:659
msgid "Calibration Age"
msgstr "Kalibreringsalder"

#: ui/autopilot_control_ui.py:556 ui/autopilot_control_ui.py:676
msgid "Clear"
msgstr "Klar"

#: ui/autopilot_control_ui.py:559 ui/autopilot_control_ui.py:679
msgid "calibration locked"
msgstr "kalibrering låst"

#: ui/autopilot_control_ui.py:582
msgid "accel"
msgstr "accelere"

#: ui/autopilot_control_ui.py:613
msgid "Sigma Points"
msgstr "Sigma poeng"

#: ui/autopilot_control_ui.py:620
msgid "local history"
msgstr "lokalhistorie"

#: ui/autopilot_control_ui.py:627
msgid "current"
msgstr "nåværende"

#: ui/autopilot_control_ui.py:634
msgid "Calibration Points"
msgstr "Kalibreringspunkter"

#: ui/autopilot_control_ui.py:703
msgid "compass"
msgstr "kompass"

#: ui/autopilot_control_ui.py:713
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr "Trykk på hver knapp når roret er i riktig posisjon for å kalibrere."

#: ui/autopilot_control_ui.py:727
msgid "Rudder"
msgstr "Ror"

#: ui/autopilot_control_ui.py:742
msgid "Reset Calibration"
msgstr "Tilbakestill kalibrering"

#: ui/autopilot_control_ui.py:752
msgid "Rudder Is Centered"
msgstr "Ror er sentrert"

#: ui/autopilot_control_ui.py:760 ui/autopilot_control_ui.py:773
#: ui/autopilot_control_ui.py:786
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:765
msgid "Rudder is Starboard Range"
msgstr "Ror er styrbord"

#: ui/autopilot_control_ui.py:768
msgid "Scale"
msgstr "Skala"

#: ui/autopilot_control_ui.py:778
msgid "Rudder is Port Range"
msgstr "Ror er havneserie"

#: ui/autopilot_control_ui.py:781
msgid "Non Linearity"
msgstr "Ikke lineæritet"

#: ui/autopilot_control_ui.py:798
msgid " range +-"
msgstr "rekkevidde + -"

#: ui/autopilot_control_ui.py:806
msgid "degrees"
msgstr "grader"

#: ui/autopilot_control_ui.py:825
msgid "rudder"
msgstr "ror"

#: ui/autopilot_control_ui.py:827
msgid "settings"
msgstr "innstillinger"

#: ui/boatplot.py:26
msgid "failed to load pywavefront:"
msgstr "mislyktes i å laste inn pywavefront:"

#: ui/boatplot.py:56
msgid "invalid display dimensions"
msgstr "ugyldige dimensjoner"

#: ui/boatplot.py:111
msgid "Did you add the pypilot_data repository?"
msgstr "Har du lagt til pypilot_data-depotet?"

#: ui/boatplot.py:161
msgid "not found, texture compass cannot be used"
msgstr "ikke funnet, teksturkompass kan ikke brukes"

#: ui/client_wx.py:48
msgid "Refresh"
msgstr "Forfriske"

#: ui/client_wx.py:190
msgid "Connected"
msgstr "Tilkoblet"

#: ui/client_wx.py:192
msgid "Disconnected"
msgstr "Frakoblet"

#: ui/client_wx.py:219
msgid "warning, invalid choice value specified"
msgstr "advarsel, ugyldig valgverdi spesifisert"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "pypilot Omfang"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Null"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skala +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Skala -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Offset \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Fryse"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Tid"

#: ui/scope_wx.py:68
msgid "values not found:"
msgstr "ikke funnet verdier:"
