# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-05-25 01:14-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:107
msgid "failed to load pilot"
msgstr "nie udało się załadować pilota"

#: pypilot/autopilot.py:110
msgid "Available Pilots"
msgstr "Dostępni piloci"

#: pypilot/autopilot.py:136
msgid "warning: failed to open special file"
msgstr "ostrzeżenie: nie udało się otworzyć specjalnego pliku"

#: pypilot/autopilot.py:136
msgid "for writing"
msgstr "do pisania"

#: pypilot/autopilot.py:137
msgid "cannot stroke the watchdog"
msgstr "nie mogę pogłaskać psa stróżującego"

#: pypilot/autopilot.py:141
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"ostrzeżenie: nie udało się wykonać procesu autopilota w czasie rzeczywistym"

#: pypilot/autopilot.py:309
msgid "server/client is running too _slowly_"
msgstr "serwer/klient działa zbyt _wolno_"

#: pypilot/autopilot.py:315
msgid "sensors is running too _slowly_"
msgstr "czujniki działają zbyt wolno"

#: pypilot/autopilot.py:365
msgid "autopilot routine is running too _slowly_"
msgstr "Procedura autopilota działa zbyt wolno"

#: pypilot/autopilot.py:370
msgid "servo is running too _slowly_"
msgstr "serwo działa zbyt wolno"

#: pypilot/boatimu.py:34
msgid "RTIMU library not detected, please install it"
msgstr "Nie wykryto biblioteki RTIMU, zainstaluj ją"

#: pypilot/boatimu.py:57
msgid "Using settings file"
msgstr "Korzystanie z pliku ustawień"

#: pypilot/boatimu.py:97
msgid "ERROR: No IMU Detected"
msgstr "BŁĄD: Nie wykryto IMU"

#: pypilot/boatimu.py:105
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "BŁĄD: IMU Init Failed, brak dostępnych danych inercyjnych"

#: pypilot/boatimu.py:127
msgid "warning, failed to make imu process realtime"
msgstr "ostrzeżenie, nie udało się wykonać procesu imu w czasie rzeczywistym"

#: pypilot/boatimu.py:129
msgid "made imu process realtime"
msgstr "wykonane imu proces w czasie rzeczywistym"

#: pypilot/boatimu.py:141
msgid "setting initial gyro bias"
msgstr "ustawienie początkowego odchylenia żyroskopu"

#: pypilot/boatimu.py:157
msgid "imu process failed to keep time"
msgstr "Proces imu nie dotrzymał czasu"

#: pypilot/boatimu.py:165
msgid "failed to read IMU!"
msgstr "nie udało się odczytać IMU!"

#: pypilot/boatimu.py:197
msgid "imu rate set to rate"
msgstr "stawka imu ustawiona na stawkę"

#: pypilot/boatimu.py:211
msgid "too high standing gyro bias, resetting sensors"
msgstr "zbyt wysokie odchylenie stojące żyroskopu, resetowanie czujników"

#: pypilot/boatimu.py:216
msgid "compass out of range, resetting"
msgstr "kompas poza zasięgiem, resetowanie"

#: pypilot/boatimu.py:308
msgid "warning, failed to make calibration process other"
msgstr "ostrzeżenie, nie udało się dokonać kalibracji w inny sposób"

#: pypilot/boatimu.py:310
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"ostrzeżenie, nie udało się przeprowadzić procesu kalibracji bezczynności, "
"próbuję renice"

#: pypilot/boatimu.py:312
msgid "warning, failed to renice calibration process"
msgstr "ostrzeżenie, nie udało się odnowić procesu kalibracji"

#: pypilot/boatimu.py:320
msgid "calibration loaded, starting"
msgstr "kalibracja załadowana, start"

#: pypilot/boatimu.py:323
msgid "failed import calibration fit"
msgstr "nieudane dopasowanie kalibracji importu"

#: pypilot/boatimu.py:339
msgid "terminate calibration process"
msgstr "zakończyć proces kalibracji"

#: pypilot/boatimu.py:429
msgid "accel values invalid"
msgstr "wartości przyspieszenia są nieprawidłowe"

#: pypilot/bufferedsocket.py:56
msgid "overflow in pypilot udp socket"
msgstr "przepełnienie w gnieździe pypilot udp"

#: pypilot/bufferedsocket.py:61
msgid "overflow in pypilot socket"
msgstr "przelew w gnieździe pypilota"

#: pypilot/bufferedsocket.py:71
msgid "failed to send udp packet"
msgstr "nie udało się wysłać pakietu UDP"

#: pypilot/bufferedsocket.py:80
msgid "pypilot socket failed to send to"
msgstr "Nie udało się wysłać gniazda pypilot do"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "wysyłanie gniazda trwało zbyt długo!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "Błąd wysyłania gniazda"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "Wyjątek gniazda pypilot"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "powrót do nieblokującego gniazda Pythona, zużyje więcej procesora c"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "błąd wysyłania gniazda w spłukiwaniu serwera"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "błąd odbierania danych"

#: pypilot/calibration_fit.py:39
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"nie udało się załadować biblioteki naukowej, nie można przeprowadzić "
"aktualizacji kalibracji!"

#: pypilot/client.py:97
msgid "warning, registering existing value:"
msgstr "ostrzeżenie, rejestracja istniejącej wartości:"

#: pypilot/client.py:155
msgid "failed to read config file:"
msgstr "nie udało się odczytać pliku konfiguracyjnego:"

#: pypilot/client.py:186
msgid "failed to write config file:"
msgstr "nie udało się zapisać pliku konfiguracyjnego:"

#: pypilot/client.py:188
msgid "Exception writing config file:"
msgstr "Plik konfiguracyjny zapisu wyjątków:"

#: pypilot/client.py:265
msgid "invalid message from server:"
msgstr "nieprawidłowa wiadomość z serwera:"

#: pypilot/client.py:281
msgid "warning, pypilot client aleady has connection"
msgstr "ostrzeżenie, klient pypilot ma już połączenie"

#: pypilot/client.py:301
msgid "connect failed to"
msgstr "nie udało się połączyć z"

#: pypilot/client.py:388
msgid "failed to connect to"
msgstr "nie udało się połączyć z"

#: pypilot/client.py:445
msgid "usage"
msgstr "stosowanie"

#: pypilot/client.py:448
msgid "set the host or ip address"
msgstr "ustaw hosta lub adres IP"

#: pypilot/client.py:449
msgid "print info about each value type"
msgstr "drukuj informacje o każdym typie wartości"

#: pypilot/client.py:450
msgid "continuous watch"
msgstr "obserwacja ciągła ."

#: pypilot/client.py:451
msgid "show this message"
msgstr "pokaż tę wiadomość"

#: pypilot/client.py:478
msgid "failed to retrieve value list!"
msgstr "nie udało się pobrać listy wartości!"

#: pypilot/client.py:489
msgid "timeout retrieving"
msgstr "Pobieranie limitu czasu"

#: pypilot/client.py:492
msgid "missing"
msgstr "brakujący"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot nie mógł zaimportować wymaganych modułów. Zapomniałeś uruchomić sudo"
" python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "podłączony GPS"

#: pypilot/gpsd.py:48
msgid "gpsd failed to connect"
msgstr "GPSd nie udało się połączyć"

#: pypilot/gpsd.py:53
msgid "exception connecting to gps"
msgstr "wyjątek w połączeniu z GPS"

#: pypilot/gpsd.py:57
msgid "gpsd disconnected"
msgstr "GPS odłączony"

#: pypilot/gpsd.py:71
msgid "gpsd PROBE success"
msgstr "Sukces SONDY GPS"

#: pypilot/gpsd.py:79
msgid "gpsd probe failed"
msgstr "sonda gpsd nie powiodła się"

#: pypilot/gpsd.py:102
msgid "gpsd deactivated"
msgstr "GPS dezaktywowany"

#: pypilot/gpsd.py:135
msgid "gpsd failed to determine serial baud rate of device"
msgstr "GPSd nie może określić szybkości transmisji szeregowej urządzenia"

#: pypilot/gpsd.py:152
msgid "gpsd timeout from lack of data"
msgstr "przekroczenie limitu czasu gpsd z powodu braku danych"

#: pypilot/gpsd.py:167
msgid "gpsd received invalid message"
msgstr "gpsd otrzymał nieprawidłową wiadomość"

#: pypilot/gpsd.py:212
msgid "gpsd got flag for pipe:"
msgstr "gpsd ma flagę dla potoku:"

#: pypilot/gpsd.py:221
msgid "gpsd serial probe"
msgstr "sonda szeregowa gpsd"

#: pypilot/nmea.py:87
msgid "nmea failed to parse gps"
msgstr "nmea nie przeanalizowała GPS"

#: pypilot/nmea.py:127
msgid "nmea failed to parse wind"
msgstr "nmea nie przeanalizowała wiatru"

#: pypilot/nmea.py:189
msgid "exception parsing apb"
msgstr "parsowanie wyjątków apb"

#: pypilot/nmea.py:277
msgid "unhandled nmea pipe string"
msgstr "nieobsługiwany ciąg rur nmea"

#: pypilot/nmea.py:327
msgid "lost serial"
msgstr "zgubiony serial"

#: pypilot/nmea.py:350
msgid "nmea got flag for process pipe:"
msgstr "nmea otrzymała flagę dla rury procesowej:"

#: pypilot/nmea.py:371
msgid "is another process accessing it?"
msgstr "czy inny proces ma do niego dostęp?"

#: pypilot/nmea.py:373
msgid "serial device timed out"
msgstr "Przekroczono limit czasu urządzenia szeregowego"

#: pypilot/nmea.py:429
msgid "failed to open"
msgstr "nie udało się otworzyć"

#: pypilot/nmea.py:482
msgid "nmea server on port"
msgstr "serwer nmea na porcie"

#: pypilot/nmea.py:482
msgid "bind failed."
msgstr "powiązanie nie powiodło się."

#: pypilot/nmea.py:484
msgid "listening on port"
msgstr "nasłuchiwanie na porcie"

#: pypilot/nmea.py:484
msgid "for nmea connections"
msgstr "dla połączeń nmea"

#: pypilot/nmea.py:550
msgid "nmea server has too many connections"
msgstr "Serwer nmea ma za dużo połączeń"

#: pypilot/nmea.py:576
msgid "nmea sock not in sockets!"
msgstr "skarpeta nmea nie jest w gniazdkach!"

#: pypilot/nmea.py:587
msgid "nmea failed to unregister socket"
msgstr "nmea nie może wyrejestrować gniazda"

#: pypilot/nmea.py:592
msgid "nmea failed to remove fd"
msgstr "nmea nie usunął fd"

#: pypilot/nmea.py:597
msgid "nmea failed to remove address"
msgstr "nmea nie udało się usunąć adresu"

#: pypilot/nmea.py:610
msgid "connected to"
msgstr "połączony z"

#: pypilot/nmea.py:610
msgid "in"
msgstr "w"

#: pypilot/nmea.py:610
msgid "seconds"
msgstr "sekundy"

#: pypilot/nmea.py:614
msgid "nmea client failed to connect to"
msgstr "Klient nmea nie połączył się z"

#: pypilot/nmea.py:641
msgid "poll took too long in nmea process!"
msgstr "ankieta trwała zbyt długo w procesie nmea!"

#: pypilot/nmea.py:648
msgid "nmea bridge lost server connection"
msgstr "nmea most utracił połączenie z serwerem"

#: pypilot/nmea.py:651
msgid "nmea bridge lost pipe to autopilot"
msgstr "most nmea zgubił rurę do autopilota"

#: pypilot/nmea.py:670
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge nieobsłużona flaga ankiety"

#: pypilot/nmea.py:707
msgid "failed to create nmea socket as host:port"
msgstr "nie udało się utworzyć gniazda nmea jako host:port"

#: pypilot/nmea.py:713
msgid "nmea process loop too slow:"
msgstr "Zbyt wolna pętla procesu nmea:"

#: pypilot/nonblockingpipe.py:41
msgid "error pipe block on recv!"
msgstr "błąd bloku potoku na recv!"

#: pypilot/nonblockingpipe.py:43
msgid "failed to recv nonblocking pipe!"
msgstr "nie udało się odebrać nieblokującego potoku!"

#: pypilot/nonblockingpipe.py:70
msgid "pipe full"
msgstr "rura pełna"

#: pypilot/nonblockingpipe.py:70
msgid "cannot send"
msgstr "nie można wysłać"

#: pypilot/nonblockingpipe.py:90 pypilot/nonblockingpipe.py:146
msgid "failed to decode data socket!"
msgstr "nie udało się zdekodować gniazda danych!"

#: pypilot/nonblockingpipe.py:104
msgid "failed to encode data socket!"
msgstr "nie udało się zakodować gniazda danych!"

#: pypilot/nonblockingpipe.py:156
msgid "failed write"
msgstr "nieudany zapis"

#: pypilot/pyjson.py:15
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"OSTRZEŻENIE: biblioteka Pythona ujson nie powiodła się, parsowanie zużyje "
"więcej procesora"

#: pypilot/rudder.py:118
msgid "bad rudder calibration"
msgstr "zła kalibracja steru"

#: pypilot/rudder.py:122
msgid "bad servo rudder calibration"
msgstr "zła kalibracja steru serwomechanizmu"

#: pypilot/rudder.py:194
msgid "servo rudder autogain failed"
msgstr "Autowzmocnienie steru serwomechanizmu nie powiodło się"

#: pypilot/sensors.py:43
msgid "sensor found"
msgstr "znaleziono czujnik"

#: pypilot/sensors.py:192
msgid "unknown data parsed!"
msgstr "przeanalizowano nieznane dane!"

#: pypilot/serialprobe.py:31
msgid "error reading"
msgstr "błąd odczytu"

#: pypilot/serialprobe.py:87
msgid "found more devices by path"
msgstr "znalazłem więcej urządzeń według ścieżki"

#: pypilot/serialprobe.py:119
msgid "removing gps device"
msgstr "usuwanie urządzenia GPS"

#: pypilot/serialprobe.py:195
msgid "no pyudev module! will scan usb devices often!"
msgstr "brak modułu pyudev! będzie często skanować urządzenia USB!"

#: pypilot/serialprobe.py:357
msgid "success"
msgstr "sukces"

#: pypilot/serialprobe.py:365
msgid "failed to record device"
msgstr "nie udało się nagrać urządzenia"

#: pypilot/server.py:97
msgid "ERROR no connections in watch"
msgstr "BŁĄD brak połączeń w zegarku"

#: pypilot/server.py:200
msgid "remove duplicate udp connection"
msgstr "usuń zduplikowane połączenie UDP"

#: pypilot/server.py:340 ui/boatplot.py:110
msgid "failed to load"
msgstr "nie udało się załadować"

#: pypilot/server.py:351
msgid "backup data failed as well"
msgstr "kopia zapasowa również nie powiodła się"

#: pypilot/server.py:379
msgid "failed to write"
msgstr "nie udało się napisać"

#: pypilot/server.py:436
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: wiązanie nie powiodło się; masz już serwer?"

#: pypilot/server.py:498
msgid "persistent store took too long!"
msgstr "uporczywe przechowywanie trwało zbyt długo!"

#: pypilot/server.py:514
msgid "max connections reached"
msgstr "osiągnięto maksymalną liczbę połączeń"

#: pypilot/server.py:517
msgid "server add socket"
msgstr "serwer dodaj gniazdo"

#: pypilot/server.py:527
msgid "internal pipe closed, server exiting"
msgstr "rura wewnętrzna zamknięta, serwer wychodzi server"

#: pypilot/server.py:579
msgid "server socket closed from flush!!"
msgstr "gniazdo serwera zamknięte od spłukiwania!!"

#: pypilot/servo.py:449
msgid "servo calibration invalid"
msgstr "kalibracja serwa jest nieprawidłowa"

#: pypilot/servo.py:557
msgid "failed to open servo on:"
msgstr "nie udało się otworzyć serwa na:"

#: pypilot/servo.py:564
msgid "failed set nonblocking/exclusive"
msgstr "nieudane ustawienie nieblokujące/wyłączne"

#: pypilot/servo.py:595
msgid "found"
msgstr "znaleziony"

#: pypilot/servo.py:716
msgid "loading servo calibration"
msgstr "kalibracja serwomechanizmu ładowania"

#: pypilot/servo.py:720
msgid "WARNING: using default servo calibration!!"
msgstr "UWAGA: używanie domyślnej kalibracji serwa!!"

#: pypilot/servo.py:729
msgid "probing"
msgstr "sondowanie"

#: pypilot/servo.py:745
msgid "arduino servo detected"
msgstr "wykryto serwo arduino"

#: pypilot/servo.py:754
msgid "device needed for option"
msgstr "urządzenie potrzebne do opcji"

#: pypilot/signalk.py:67
msgid "read token"
msgstr "przeczytaj token"

#: pypilot/signalk.py:70
msgid "failed to read token"
msgstr "nie udało się odczytać tokena"

#: pypilot/signalk.py:77
msgid "failed to"
msgstr "nie udało się"

#: pypilot/signalk.py:77
msgid "autodetection not possible"
msgstr "autodetekcja nie jest możliwa"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "try"
msgstr "próbować"

#: pypilot/signalk.py:78 pypilot/signalk.py:144 pypilot/signalk.py:213
msgid "or"
msgstr "lub"

#: pypilot/signalk.py:109
msgid "service removed"
msgstr "usługa usunięta"

#: pypilot/signalk.py:113
msgid "signalk server lost"
msgstr "serwer sygnałowy zgubiony!"

#: pypilot/signalk.py:116
msgid "service add"
msgstr "usługa add"

#: pypilot/signalk.py:130
msgid "server found"
msgstr "znaleziono serwer"

#: pypilot/signalk.py:139
msgid "probe"
msgstr "sonda"

#: pypilot/signalk.py:143
msgid "could not"
msgstr "nie móc"

#: pypilot/signalk.py:153
msgid "failed to retrieve/parse data from"
msgstr "nie udało się pobrać/przeanalizować danych z"

#: pypilot/signalk.py:156
msgid "signalk found"
msgstr "znaleziono sygnał"

#: pypilot/signalk.py:168
msgid "see if token is ready"
msgstr "zobacz, czy token jest gotowy"

#: pypilot/signalk.py:174
msgid "received token"
msgstr "otrzymany token"

#: pypilot/signalk.py:180
msgid "failed to store token"
msgstr "nie udało się zapisać tokena"

#: pypilot/signalk.py:184
msgid "error requesting access"
msgstr "błąd podczas żądania dostępu"

#: pypilot/signalk.py:203
msgid "signalk request access url"
msgstr "adres URL żądania sygnału"

#: pypilot/signalk.py:205
msgid "signalk error requesting access"
msgstr "błąd sygnału podczas żądania dostępu"

#: pypilot/signalk.py:212
msgid "cannot create connection:"
msgstr "nie można utworzyć połączenia:"

#: pypilot/signalk.py:226
msgid "failed to connect"
msgstr "nie udało się połączyć"

#: pypilot/signalk.py:270
msgid "signalk connected to"
msgstr "sygnał podłączony do"

#: pypilot/signalk.py:313
msgid "signalk failed to parse"
msgstr "Signalk nie przeanalizował"

#: pypilot/signalk.py:331
msgid "Exception converting signalk->pypilot"
msgstr "Wyjątek konwertujący sygnał->pypilot"

#: pypilot/signalk.py:345
msgid "received"
msgstr "Odebrane"

#: pypilot/signalk.py:391
msgid "signalk failed to send"
msgstr "nie udało się wysłać sygnału"

#: pypilot/signalk.py:404
msgid "signalk failed to parse msg:"
msgstr "signalk nie przeanalizował wiadomości:"

#: pypilot/values.py:131
msgid "invalid initial value for range property"
msgstr "nieprawidłowa wartość początkowa właściwości zakresu range"

#: pypilot/values.py:180
msgid "invalid set"
msgstr "nieprawidłowy zestaw"

#: pypilot/pilots/__init__.py:25
msgid "ERROR loading"
msgstr "Błąd ładowania"

#: ui/autopilot_calibration.py:167
msgid "exception in calibration:"
msgstr "wyjątek w kalibracji:"

#: ui/autopilot_control.py:265
msgid "warning: unhandled message"
msgstr "ostrzeżenie: nieobsłużona wiadomość"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Kontrola autopilota"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "ty"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:455 ui/autopilot_control_ui.py:732
msgid "N/A"
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "Port"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "sterburta"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:420
msgid "Compass"
msgstr "Kompas"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Wiatr"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Prawdziwy wiatr"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Środek"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Zakres"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrowanie"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Blisko"

#: ui/autopilot_control_ui.py:299 ui/autopilot_control_ui.py:529
#: ui/autopilot_control_ui.py:649
msgid "Calibration"
msgstr "Kalibrowanie"

#: ui/autopilot_control_ui.py:349
msgid "Boat is level"
msgstr "Łódź jest wypoziomowana"

#: ui/autopilot_control_ui.py:356 ui/client_wx.py:159 ui/scope_ui.py:94
msgid "Reset"
msgstr "Resetowanie"

#: ui/autopilot_control_ui.py:377
msgid "Alignment"
msgstr "Wyrównanie"

#: ui/autopilot_control_ui.py:394
msgid "Heading"
msgstr "Nagłówek"

#: ui/autopilot_control_ui.py:399 ui/autopilot_control_ui.py:465
#: ui/autopilot_control_ui.py:475
msgid "     N/A     "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:755
msgid "Offset"
msgstr "Offsetowy"

#: ui/autopilot_control_ui.py:418
msgid "Coords"
msgstr "Współrzędne"

#: ui/autopilot_control_ui.py:420
msgid "Sea"
msgstr "Morze"

#: ui/autopilot_control_ui.py:420
msgid "Boat"
msgstr "Łódź"

#: ui/autopilot_control_ui.py:443 ui/client_wx.py:52
msgid "Scope"
msgstr "Zakres"

#: ui/autopilot_control_ui.py:450
msgid "Pitch"
msgstr "Smoła"

#: ui/autopilot_control_ui.py:460
msgid "Roll"
msgstr "Rolka"

#: ui/autopilot_control_ui.py:470
msgid "Heel"
msgstr "Obcas"

#: ui/autopilot_control_ui.py:497
msgid "alignment"
msgstr "wyrównanie"

#: ui/autopilot_control_ui.py:539 ui/autopilot_control_ui.py:659
msgid "Calibration Age"
msgstr "Wiek kalibracji"

#: ui/autopilot_control_ui.py:556 ui/autopilot_control_ui.py:676
msgid "Clear"
msgstr "Jasny"

#: ui/autopilot_control_ui.py:559 ui/autopilot_control_ui.py:679
msgid "calibration locked"
msgstr "kalibracja zablokowana"

#: ui/autopilot_control_ui.py:582
msgid "accel"
msgstr "przyspieszać"

#: ui/autopilot_control_ui.py:613
msgid "Sigma Points"
msgstr "Punkty Sigma"

#: ui/autopilot_control_ui.py:620
msgid "local history"
msgstr "lokalna historia"

#: ui/autopilot_control_ui.py:627
msgid "current"
msgstr "obecny"

#: ui/autopilot_control_ui.py:634
msgid "Calibration Points"
msgstr "Punkty kalibracji"

#: ui/autopilot_control_ui.py:703
msgid "compass"
msgstr "kompas"

#: ui/autopilot_control_ui.py:713
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Naciśnij każdy przycisk, gdy ster znajduje się w prawidłowej pozycji, aby "
"przeprowadzić kalibrację."

#: ui/autopilot_control_ui.py:727
msgid "Rudder"
msgstr "Ster"

#: ui/autopilot_control_ui.py:742
msgid "Reset Calibration"
msgstr "Zresetuj kalibrację"

#: ui/autopilot_control_ui.py:752
msgid "Rudder Is Centered"
msgstr "Ster jest wyśrodkowany"

#: ui/autopilot_control_ui.py:760 ui/autopilot_control_ui.py:773
#: ui/autopilot_control_ui.py:786
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:765
msgid "Rudder is Starboard Range"
msgstr "Ster ma zasięg na sterburcie"

#: ui/autopilot_control_ui.py:768
msgid "Scale"
msgstr "Skala"

#: ui/autopilot_control_ui.py:778
msgid "Rudder is Port Range"
msgstr "Ster ma zakres lewy ."

#: ui/autopilot_control_ui.py:781
msgid "Non Linearity"
msgstr "Nieliniowość"

#: ui/autopilot_control_ui.py:798
msgid " range +-"
msgstr "zasięg +-"

#: ui/autopilot_control_ui.py:806
msgid "degrees"
msgstr "stopnie"

#: ui/autopilot_control_ui.py:825
msgid "rudder"
msgstr "ster"

#: ui/autopilot_control_ui.py:827
msgid "settings"
msgstr "ustawienia"

#: ui/boatplot.py:26
msgid "failed to load pywavefront:"
msgstr "nie udało się załadować pywavefronta:"

#: ui/boatplot.py:56
msgid "invalid display dimensions"
msgstr "nieprawidłowe wymiary wyświetlacza"

#: ui/boatplot.py:111
msgid "Did you add the pypilot_data repository?"
msgstr "Czy dodałeś repozytorium pypilot_data?"

#: ui/boatplot.py:161
msgid "not found, texture compass cannot be used"
msgstr "nie znaleziono, nie można użyć kompasu teksturowego"

#: ui/client_wx.py:48
msgid "Refresh"
msgstr "Odświeżać"

#: ui/client_wx.py:190
msgid "Connected"
msgstr "Połączony"

#: ui/client_wx.py:192
msgid "Disconnected"
msgstr "Niepowiązany"

#: ui/client_wx.py:219
msgid "warning, invalid choice value specified"
msgstr "ostrzeżenie, podano nieprawidłową wartość wyboru"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "Zakres pypilota"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Zero"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skala +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Skala -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Przesunięcie /\\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Przesunięcie \\/"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Zamrażać"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Czas"

#: ui/scope_wx.py:68
msgid "values not found:"
msgstr "nie znaleziono wartości:"
